// AUTO-GENERATED by vite-plugin-text-types. DO NOT EDIT.
export const texts = {
  "another.txt": "I'm just a text file!\n",
  "hello.md": "# Hello {{name}}\n\nThis is an example markdown file for {{name}}.\n",
} as const;

type Trim<T extends string> = T extends ` ${infer R}` ? Trim<R> : T extends `${infer L} ` ? Trim<L> : T;
type ExtractVars<T extends string> = T extends `${string}{{${infer Prop}}}${infer Rest}`
  ? Trim<Prop> | ExtractVars<Rest>
  : never;

export function getText<K extends keyof typeof texts>(
  id: K,
  ...args: ExtractVars<(typeof texts)[K]> extends never
    ? []
    : [vars: { [P in ExtractVars<(typeof texts)[K]>]: string | number }]
): string {
  const t: string = texts[id];
  const vars = args[0];
  if (!vars) return t;
  return t.replace(new RegExp("\\{\\{([\\s\\S]+?)\\}\\}", 'g'), (_, key) => {
    const val = (vars as any)[key.trim()];
    return val !== undefined ? String(val) : "{{" + key + "}}";
  });
}